webtalk_init -webtalk_dir /home/admin1/VMlabCN/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/sim_N2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 14 17:18:34 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "05cb3ff0-83e8-4ff5-8c2e-1ecfd683aa16" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c168c8898612439b8457eeaf75eb6a33" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Zorin" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Zorin OS 16" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116720_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3699492248 -regid "" -xml /home/admin1/VMlabCN/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/sim_N2_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/admin1/VMlabCN/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/sim_N2_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/admin1/VMlabCN/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/sim_N2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
