#Mirica Victor-Nicolae <victor.mirica@stud.acs.upb.ro>

build:
	javac src/*.java

run-p1:
	java -cp ./src Walsh

run-p2:
	java -cp ./src Statistics

run-p3:
	java -cp ./src Prinel

run-p4:
	java -cp ./src Crypto

clean:
	$(RM) src/*.class