# MIRICA Victor - 315CB 
build: 
	gcc -Wall functiiArb.c main.c -o tema3 -std=c99
run:
	./tema3 in_file out_file
runv:
	valgrind --leak-check=full --track-origins=yes ./tema3 in_file out_file
clean:
	rm -rf tema3