# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/admin1/VMlabCN/lab1/lab1.srcs/sources_1/bd/design_3/ip/design_3_ila_0_0/design_3_ila_0_0.xci
# IP: The module: 'design_3_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/admin1/VMlabCN/lab1/lab1.gen/sources_1/bd/design_3/ip/design_3_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/admin1/VMlabCN/lab1/lab1.gen/sources_1/bd/design_3/ip/design_3_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/admin1/VMlabCN/lab1/lab1.gen/sources_1/bd/design_3/ip/design_3_ila_0_0/design_3_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/admin1/VMlabCN/lab1/lab1.srcs/sources_1/bd/design_3/ip/design_3_ila_0_0/design_3_ila_0_0.xci
# IP: The module: 'design_3_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/admin1/VMlabCN/lab1/lab1.gen/sources_1/bd/design_3/ip/design_3_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/admin1/VMlabCN/lab1/lab1.gen/sources_1/bd/design_3/ip/design_3_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/admin1/VMlabCN/lab1/lab1.gen/sources_1/bd/design_3/ip/design_3_ila_0_0/design_3_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
