# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project3/Nexys4DDR_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_divizor_ceas_0_0/design_1_divizor_ceas_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_divizor_ceas_0_0 || ORIG_REF_NAME==design_1_divizor_ceas_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bin2bcd_0_0/design_1_bin2bcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bin2bcd_0_0 || ORIG_REF_NAME==design_1_bin2bcd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bin2bcd_1_0/design_1_bin2bcd_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bin2bcd_1_0 || ORIG_REF_NAME==design_1_bin2bcd_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_afisare_7seg_0_0/design_1_afisare_7seg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_afisare_7seg_0_0 || ORIG_REF_NAME==design_1_afisare_7seg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_numarator_59_0_0/design_1_numarator_59_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_numarator_59_0_0 || ORIG_REF_NAME==design_1_numarator_59_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_numarator_59_1_0/design_1_numarator_59_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_numarator_59_1_0 || ORIG_REF_NAME==design_1_numarator_59_1_0} -quiet] -quiet

# XDC: c:/Users/student/Desktop/VMLabCN/lucrare2/lucrare2.gen/sources_1/bd/design_1/design_1_ooc.xdc
