#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 14 16:37:58 EET 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sim_N2_behav -key {Behavioral:sim_1:Functional:sim_N2} -tclbatch sim_N2.tcl -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim sim_N2_behav -key {Behavioral:sim_1:Functional:sim_N2} -tclbatch sim_N2.tcl -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

