#Mirica Victor-Nicolae <victor.mirica@stud.acs.upb.ro>

build:
	javac src/*.java

run-p1:
	java -cp ./src Curatare

run-p2:
	java -cp ./src Fortificatii

run-p3:
	java -cp ./src Beamdrone

run-p4:
	java -cp ./src Curse

clean:
	$(RM) src/*.class